name: "Test Issue Template"
title: "Test Issue Template Title"
description: |
  Sample description does _not_ render markdown in the "new issue dialog".
labels: ["what"]  
body:
  - type: markdown
    attributes:
      value: |
        ## Sample Markdown Section
        This is a sample section that uses **bold** and _italic_ text.

        Diagrams don't work?

        ```mermaid
        flowchart
          A --> B
          B --> C
          C --> A
        ```

  - type: input
    id: sample_input # can be passed on the query string
    attributes:
      label: "Sample Input"
      description: "This is a sample input field."
      placeholder: "Enter something here..."


  - type: checkboxes
    attributes:
      label: "Steps to do a thing"
      description: |
        This is a sample checkboxes section that uses _markdown_ just fine.
      options:
        - label: step 1
        - label: |
            step 2 uses _markdown_ just fine.