name: Deploy
concurrency: deploy

on:
  release:
    types: [published]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo ${{ github.event.base_ref }}
      - run: echo ${{ github.event.ref }}
      - run: echo ${{ github.event }}

  staging:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || (
        github.event_name == 'workflow_dispatch' && 
        github.event.inputs.environment == 'staging'
      )
    environment: staging
    needs: build
    steps:
      - run: echo "TODO deploy staging iff we're a push or a manual trigger on ${{ github.event.repository.default_branch }}"

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - run: echo "TODO deploy production iff we're a release or a manual trigger on a tag"