name: Self-tag
concurrency: self-tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tag
        run: |
          export VERSION=$(date +%s)
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
